#!/usr/bin/env bash
# nginx install
sudo apt -y update
sudo apt-get -y install nginx
sudo chown -R ubuntu:ubuntu /var/www/html
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx start
