#!/usr/bin/env bash
# This script is displaying numbers from 1 to 20
i=1; while [ $i -le 20 ];do echo $i; i=$((i + 1));case $i in 5 ) echo 'bad luck from China';; 18 ) echo "bad luck from Italy" ;; 10) echo "bad luck from Japan";; esac; done

