#!/usr/bin/env bash
# This script gives you information about the holbertonschool file.
FILE=holbertonschool;if test -e $FILE; then echo "$FILE file exists";if [ -s $FILE ]; then echo holbertonschool file is not empty; else echo holbertonschool file is empty;fi;if test -f $FILE ;then echo holbertonschool is a regular file;fi;else echo "$FILE file does not exist";  fi